general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
}
decoration {
    rounding = 12
    active_opacity = 1.0
    inactive_opacity = 1.0
    blur {
        size = 4
        passes = 2
    }
}
