-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#121318",
	base01 = "#0d0e13",
	base02 = "#1a1b21",
	base03 = "#45464f",
	base04 = "#c5c6d0",
	base05 = "#e3e2e9",
	base06 = "#2f3036",
	base07 = "#38393f",

	base08 = "#daa9d2",
	base09 = "#e2bbdb",
	base0A = "#c1c5dd",
	base0B = "#b4c5ff",
	base0C = "#5b3d58",
	base0D = "#334478",
	base0E = "#414659",
	base0F = "#a0a6cb",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#334478",
	fg = "#dbe1ff", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#cb85bf",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#8f909a",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#e2bbdb",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#c1c5dd",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#4b5c92",
})
