#!/bin/bash
# Pywal hook: generate swaylock config with current colors

SWAYLOCK_CONF="$HOME/.config/swaylock/config"
WALLPAPER="$HOME/.cache/wal/wal"

# Load pywal16 colors
. "${HOME}/.cache/wal/colors.sh"

cat > "$SWAYLOCK_CONF" <<EOF
# Auto-generated by pywal hook

image=$WALLPAPER
scaling=fill

inside-color=$color0
inside-clear-color=$color4
inside-ver-color=$color2
inside-wrong-color=$color1

ring-color=$color8
ring-clear-color=$color4
ring-ver-color=$color2
ring-wrong-color=$color1

key-hl-color=$color7
bs-hl-color=$color3

separator-color=00000000

text-color=$color15
text-clear-color=$color15
text-ver-color=$color15
text-wrong-color=$color15

indicator-idle-visible=yes
indicator-caps-lock=yes
indicator-radius=100
indicator-thickness=10

show-failed-attempts=yes
show-keyboard-layout=yes
daemonize
EOF

