-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#171217",
	base01 = "#110d11",
	base02 = "#1f1a1f",
	base03 = "#4d444c",
	base04 = "#d0c3cc",
	base05 = "#eadfe6",
	base06 = "#352f34",
	base07 = "#3e373d",

	base08 = "#f3a497",
	base09 = "#f6b8ae",
	base0A = "#d7bfd5",
	base0B = "#ebb5ed",
	base0C = "#673b34",
	base0D = "#613766",
	base0E = "#534153",
	base0F = "#c3a0c0",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#613766",
	fg = "#ffd6fe", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#ee7c69",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#998d96",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#f6b8ae",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#d7bfd5",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#7b4e7f",
})
