-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#19120d',
  base01 = '#140d08',
  base02 = '#221a15',
  base03 = '#52443c',
  base04 = '#d7c3b8',
  base05 = '#f0dfd7',
  base06 = '#382e29',
  base07 = '#413731',

  base08 = '#ffb4ab',
  base09 = '#caca93',
  base0A = '#e5bfa9',
  base0B = '#ffb688',
  base0C = '#48491e',
  base0D = '#6e380f',
  base0E = '#5b4130',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#6e380f',
  fg = '#19120d',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#e7e6ad',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#caca93',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e5bfa9',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#8b4f24',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#140d08',
  fg = '#ffb688',
})
