-- Auto-generated by Matugen (Material 3 Expressive)

require('base16-colorscheme').setup({
  base00 = '#141318',
  base01 = '#0f0d13',
  base02 = '#cdbdff',
  base03 = '#938f99',
  base04 = '#cac4cf',
  base05 = '#e6e1e9',
  base06 = '#e6e1e9',
  base07 = '#3a383e',

  base08 = '#ffb4ab',
  base09 = '#eeb8ca',
  base0A = '#cbc3dc',
  base0B = '#cdbdff',
  base0C = '#633b4a',
  base0D = '#4b3e76',
  base0E = '#494458',
  base0F = '#93000a',
})

-- Helper function
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Material 3 Expressive highlights (FIXED)
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#4b3e76',
  fg = '#e8deff',
})

-- Comments → tertiary (your request)
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#eeb8ca',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#633b4a',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#cdbdff',
})

-- Keyword with bold style (FIXED syntax)
vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#cdbdff',
  bold = true,  -- ✅ Correct syntax
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0f0d13',
  fg = '#cdbdff',
})


-- Telescope Material 3 Expressive theming
vim.api.nvim_set_hl(0, 'TelescopeNormal', {
  bg = '#141318',
  fg = '#e6e1e9',
})

vim.api.nvim_set_hl(0, 'TelescopeBorder', {
  bg = '#141318',
  fg = '#938f99',  -- Outline for clean borders
})

vim.api.nvim_set_hl(0, 'TelescopePromptBorder', {
  bg = '#1c1b20',
  fg = '#cdbdff',   -- Primary accent
})

vim.api.nvim_set_hl(0, 'TelescopePromptNormal', {
  bg = '#1c1b20',
  fg = '#cac4cf',
})

vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', {
  bg = '#1c1b20',
  fg = '#cdbdff',    -- Vibrant prompt cursor
})

vim.api.nvim_set_hl(0, 'TelescopeSelection', {
  bg = '#4b3e76',
  fg = '#e8deff',  -- Matches Visual
})

vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', {
  bg = '#cdbdff',
  fg = '#cdbdff',
})

vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', {
  bg = '#3a383e',
  fg = '#cdbdff',
})

vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', {
  bg = '#4b3e76',
  fg = '#e8deff',
})

vim.api.nvim_set_hl(0, 'TelescopeMatching', {
  fg = '#cdbdff',  -- Highlight matches
})

-- Lazy.nvim Material 3 Expressive UI
vim.api.nvim_set_hl(0, 'LazyNormal', {
  bg = '#141318',
  fg = '#e6e1e9',
})

vim.api.nvim_set_hl(0, 'LazyBorder', {
  bg = '#141318',
  fg = '#938f99',  -- Clean outline borders
})

vim.api.nvim_set_hl(0, 'LazyHeader', {
  bg = '#4b3e76',
  fg = '#e8deff',
})

vim.api.nvim_set_hl(0, 'LazyReasonPlugin', { fg = '#cdbdff' })
vim.api.nvim_set_hl(0, 'LazyReasonSource', { fg = '#cbc3dc' })
vim.api.nvim_set_hl(0, 'LazyCommit', { fg = '#eeb8ca' })

vim.api.nvim_set_hl(0, 'LazyH1', {
  fg = '#cdbdff',
  bold = true,
})

-- Mason.nvim Material 3 Expressive UI  
vim.api.nvim_set_hl(0, 'MasonHeader', {
  bg = '#4b3e76',
  fg = '#e8deff',
})

vim.api.nvim_set_hl(0, 'MasonHeaderSecondary', {
  bg = '#3a383e',
  fg = '#e6e1e9',
})

vim.api.nvim_set_hl(0, 'MasonNormal', {
  bg = '#141318',
  fg = '#e6e1e9',
})

vim.api.nvim_set_hl(0, 'MasonBorder', {
  bg = '#141318',
  fg = '#938f99',
})

vim.api.nvim_set_hl(0, 'MasonTitle', {
  fg = '#cdbdff',
  bold = true,
})

vim.api.nvim_set_hl(0, 'MasonInstalled', { fg = '#cdbdff' })
vim.api.nvim_set_hl(0, 'MasonUninstalled', { fg = '#cac4cf' })
vim.api.nvim_set_hl(0, 'MasonCommit', { fg = '#eeb8ca' })

-- Lazy.nvim window highlights (must have ui.border = "rounded")
vim.api.nvim_set_hl(0, 'LazyWin', { bg = '#141318' })
vim.api.nvim_set_hl(0, 'LazyFloat', { bg = '#141318' })

-- Mason.nvim window highlights  
vim.api.nvim_set_hl(0, 'MasonNormalFloat', { bg = '#141318' })
vim.api.nvim_set_hl(0, 'MasonBorder', { fg = '#938f99' })

-- GLOBAL FLOAT BORDERS (affects Lazy/Mason/Telescope)
vim.api.nvim_set_hl(0, 'FloatBorder', {
  bg = '#141318',
  fg = '#938f99',  -- Material 3 outline
})

-- Lazy.nvim specific floats
vim.api.nvim_set_hl(0, 'LazyFloatNormal', {
  bg = '#141318',
  fg = '#e6e1e9',
})

-- Mason.nvim specific floats  
vim.api.nvim_set_hl(0, 'MasonFloat', {
  bg = '#141318',
})

-- Fallback for all plugin floats
vim.api.nvim_set_hl(0, 'NormalFloat', {
  bg = '#141318',
})

