# backend
backend = "glx"
vsync = true #false
fading = true
# round corners
corner-radius =4

# fade (legacy, harmless to keep)
fade-delta = 8

# exclude stuff
#rounded-corners-exclude = [
#  "window_type = 'dock'",
#  "window_type = 'desktop'",
#];

#################################
#        ANIMATIONS (v12+)      #
#################################

animations = (

#################################
# Geometry change (keep yours)
#################################
    {
    triggers = [ "geometry" ];
    duration = "1.15";
    preset = "appear";
    #preset = "geometry-change";
    scale = "1.0";
    offset-y = {
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
    duration = 0.15;
    start    = "window-height";
    end      = 0;
    };
    offset-x = "offset-y";
    shadow-offset-y = "offset-y";
    shadow-offset-x = "offset-x";
    },

#################################
# OPEN → slide up + fade + slight zoom
#################################
{
  triggers = ["open" ];
  opacity = {
    duration = 0.15;
    curve = "cubic-bezier(0, 0, 0.58, 1)";
    start = 0;
    end = "window-raw-opacity";
  };
  offset-y = {
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      duration = 0.15;
    start    = "window-height";
    end      = 0;
  };
  shadow-offset-y = "offset-y";
},


{
  triggers = ["show"];
  opacity = {
    duration = 0.25;
    curve = "cubic-bezier(0.42, 0, 1, 1)";
    start = 0;
    end = "window-raw-opacity";
  };

  #offset-x = {
    #curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      #duration = 0.15;
    #start    = "window-width";
    #end      = "windowoffset-x";
  #};
  #shadow-offset-x = "offset-x";
  preset="appear";
  scale="1.0";
  duration="0.5";
},
#################################
# CLOSE → slide down + fade
#################################
{
  triggers = ["close"];

  opacity = {
    duration = 0.15;
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      start    = "window-raw-opacity-before";
    end      = 0;
  };
  offset-y = {
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      duration = 0.5;
    end      = "window-height";
    start    = 0;
  };
  shadow-offset-y = "offset-y";
},

{
  triggers = ["hide"];
  opacity = {
    curve = "cubic-bezier(0, 0, 0.58, 1)";
    start = "window-raw-opacity-before";
    end = 0;
  };
  #offset-x = {
    #curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
    #duration = 0.15;
    #start    = "window-width";
    #end      = "windowoffset-x";
  #};
  ##shadow-offset-x = "offset-x";
  preset="disappear";
  scale="1.0";
}
);

#################################
#            RULES              #
#################################

#opacity-rule = [
#  "80:class_g = 'Sakura'"
#];

#opacity-rule = [
#  "80:class_g = 'firefox'"
#];

blur:
{
  #method = "gaussian";
  size = 2; #16
  deviation = 0.069;
  method = "dual_kawase";
  strength = 12; #8
};
rules = (
  {
    match = "class_g = 'Rofi'";
    animations = (
      {
        triggers = [ "open", "show" ];
        opacity = {
          duration = 0.25;
          curve    = "cubic-bezier(0, 0.5, 0.75, 1)";
          start    = 0.0;
          end      = "window-raw-opacity";
        };
      },
      {
        triggers = [ "close", "hide" ];
        opacity = {
          duration = 0.5;
          curve    = "cubic-bezier(0, 0.8, 0.9, 1)";
          start    = "window-raw-opacity-before";
          end      = 0.0;
        };
      }
    );
  },
  { match = "fullscreen"; corner-radius = 0; },
  { match = "window_type = 'dock'"; corner-radius = 0; },
  { match = "window_type = 'desktop'"; corner-radius = 0; },
  {
    match = "class_g = 'code-oss'";
      opacity = 0.9;
  }
);
