# backend
backend = "glx"
vsync = true #false

# round corners
corner-radius = 4

# fade (legacy, harmless to keep)
fade-delta = 5

# exclude stuff
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
];

#################################
#        ANIMATIONS (v12+)      #
#################################

animations = (

#################################
# Geometry change (keep yours)
#################################
    {
    triggers = [ "geometry" ];
#preset = "appear";
#scale = "0.75";
    duration = "0.25";
#direction = "down";
    preset = "geometry-change";
    #preset = "appear";
    scale = "1.0";
    },

#################################
# OPEN → slide up + fade + slight zoom
#################################
    {
    triggers = ["open" ];

    opacity = {
      duration = 0.25;
      curve = "cubic-bezier(0.2, 0.8, 0.2, 1)";
      start = 0;
      end = "window-raw-opacity";
    };
    preset = "slide-in";
    direction = "down";
    },
{
  triggers = ["show"];
  opacity = {
    duration = 0.25;
    curve = "cubic-bezier(0, 0.8, 0.9, 1)";
    start = 0;
    end = "window-raw-opacity";
  };

    preset = "slide-in";
    direction = "down";
},
#################################
# CLOSE → slide down + fade
#################################
{
  triggers = ["close"];

  opacity = {
    duration = 0.25;
    curve = "linear";
    start = "window-raw-opacity-before";
    end = 0;
  };
    preset = "slide-out";
    direction = "down";
},

{
  triggers = ["hide"];
  opacity = {
    duration = 0.25;
    curve = "linear";
    start = "window-raw-opacity-before";
    end = 0;
  };
    preset = "slide-out";
    direction = "down";
}
);

#################################
#            RULES              #
#################################

opacity-rule = [
  "80:class_g = 'Sakura'"
];

#opacity-rule = [
#  "80:class_g = 'firefox'"
#];

blur:
{
  method = "dual_kawase";
#size = 20;
#deviation = 15.0;
#strength = 10;
  size = 25;
  deviation = 25.0;
  strength = 15;
};
