#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#autostart apps
sleep 0.2s && ~/.config/bspwm/autostart.sh

# bspwm config
bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.6
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc settings focused_border_color #ffffff

#dwindle layut
bspc config automatic_scheme
longest_side
bspc config initial_polarity
second_child

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a zen desktop='^1'
bspc rule -a brave-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
