#!/bin/bash

# Path to the colors file generated by wal
WAL_COLORS_FILE="$HOME/.cache/wal/colors-waybar.css"

# CSS file to update
CSS_FILE="$HOME/.config/wlogout/style.css"

# Check if wal colors file exists
if [[ ! -f "$WAL_COLORS_FILE" ]]; then
    echo "Wal colors file not found: $WAL_COLORS_FILE"
    exit 1
fi

# Read colors from the wal colors file
readarray -t colors < "$WAL_COLORS_FILE"

# Create an associative array to map colors
declare -A color_map
color_map[foreground]=${colors[0]}
color_map[background]=${colors[1]}
color_map[color0]=${colors[1]}
color_map[color1]=${colors[2]}
color_map[color2]=${colors[3]}
color_map[color3]=${colors[4]}
color_map[color4]=${colors[5]}
color_map[color5]=${colors[6]}
color_map[color6]=${colors[7]}
color_map[color7]=${colors[8]}
color_map[color8]=${colors[9]}
color_map[color9]=${colors[10]}
color_map[color10]=${colors[11]}
color_map[color11]=${colors[12]}
color_map[color12]=${colors[13]}
color_map[color13]=${colors[14]}
color_map[color14]=${colors[15]}
color_map[color15]=${colors[16]}

# Update the CSS file with the new colors
sed -i.bak \
    -e "s/@define-color foreground.*/@define-color foreground ${color_map[foreground]};/g" \
    -e "s/@define-color background.*/@define-color background ${color_map[background]};/g" \
    -e "s/@define-color color0.*/@define-color color0 ${color_map[color0]};/g" \
    -e "s/@define-color color1.*/@define-color color1 ${color_map[color1]};/g" \
    -e "s/@define-color color2.*/@define-color color2 ${color_map[color2]};/g" \
    -e "s/@define-color color3.*/@define-color color3 ${color_map[color3]};/g" \
    -e "s/@define-color color4.*/@define-color color4 ${color_map[color4]};/g" \
    -e "s/@define-color color5.*/@define-color color5 ${color_map[color5]};/g" \
    -e "s/@define-color color6.*/@define-color color6 ${color_map[color6]};/g" \
    -e "s/@define-color color7.*/@define-color color7 ${color_map[color7]};/g" \
    -e "s/@define-color color8.*/@define-color color8 ${color_map[color8]};/g" \
    -e "s/@define-color color9.*/@define-color color9 ${color_map[color9]};/g" \
    -e "s/@define-color color10.*/@define-color color10 ${color_map[color10]};/g" \
    -e "s/@define-color color11.*/@define-color color11 ${color_map[color11]};/g" \
    -e "s/@define-color color12.*/@define-color color12 ${color_map[color12]};/g" \
    -e "s/@define-color color13.*/@define-color color13 ${color_map[color13]};/g" \
    -e "s/@define-color color14.*/@define-color color14 ${color_map[color14]};/g" \
    -e "s/@define-color color15.*/@define-color color15 ${color_map[color15]};/g" \
    "$CSS_FILE"

echo "Updated $CSS_FILE with colors from $WAL_COLORS_FILE"
