-- Auto-generated by Matugen - Neovim Base16 + UI overrides
local base16 = require("base16-colorscheme")
base16.setup({
  base00 = "#131318"
  base01 = "#0e0e13"
  base02 = "#1c1b20"
  base03 = "#928f99"
  base04 = "#c8c5d0"
  base05 = "#e5e1e9"
  base06 = "#e5e1e9"
  base07 = "#3a383f"
  base08 = "#ffb4ab"
  base09 = "#ebb8cf"
  base0A = "#c8c4dc"
  base0B = "#c5c0ff"
  base0C = "#613b4e"
  base0D = "#444078"
  base0E = "#474459"
  base0F = "#93000a"
})

-- Semantic UI colors
local C = {
  bg = "#131318",
  surface = "#1c1b20",
  focus = "#c5c0ff",
  text = "#e5e1e9",
  subtle = "#c8c5d0"
}

-- Apply highlights
vim.api.nvim_set_hl(0, "Normal", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "LineNr", { fg = C.subtle })
vim.api.nvim_set_hl(0, "Visual", { bg = "#444078", fg = "#e4dfff" })

