-- Auto-generated by Matugen (Material 3 Expressive)
-- Neovim Base16 + UI semantic overrides

require("base16-colorscheme").setup({
  -- Base palette
  base00 = "#141318",
  base01 = "#0e0d13",
  base02 = "#1c1b20",
  base03 = "#928f99",
  base04 = "#c9c5d0",
  base05 = "#e5e1e9",
  base06 = "#e5e1e9",
  base07 = "#3a383e",

  -- Syntax
  base08 = "#ffb4ab",
  base09 = "#ecb8ce",
  base0A = "#c9c3dc",
  base0B = "#c8bfff",
  base0C = "#613b4d",
  base0D = "#473f77",
  base0E = "#474459",
  base0F = "#93000a",
})

---------------------------------------------------------------------
-- Helpers
---------------------------------------------------------------------
local function set_hl(groups, opts)
  for _, g in ipairs(groups) do
    vim.api.nvim_set_hl(0, g, opts)
  end
end

---------------------------------------------------------------------
-- Semantic UI tokens (THIS is what was missing)
---------------------------------------------------------------------
local C = {
  bg        = "#141318",
  surface   = "#1c1b20",
  surface2  = "#0e0d13",
  focus     = "#c8bfff",
  focus_fg  = "#30285f",
  subtle    = "#c9c5d0",
  text      = "#e5e1e9",
}

---------------------------------------------------------------------
-- Core editor
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "Normal", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "Visual", {
  bg = "#473f77",
  fg = "#e5deff",
})

vim.api.nvim_set_hl(0, "LineNr", { fg = C.subtle })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = C.focus, bold = true })

---------------------------------------------------------------------
-- Treesitter (modern capture groups)
---------------------------------------------------------------------
set_hl({ "@comment", "Comment" }, { fg = "#ecb8ce", italic = true })
set_hl({ "@function", "Function" }, { fg = "#c8bfff" })
set_hl({ "@method" }, { fg = "#613b4d" })
vim.api.nvim_set_hl(0, "Keyword", { fg = C.focus, bold = true })

---------------------------------------------------------------------
-- Floats
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "NormalFloat", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = C.bg, fg = "#928f99" })

---------------------------------------------------------------------
-- Telescope
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = C.surface, fg = C.subtle })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = C.surface, fg = C.focus })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { bg = C.surface, fg = C.focus })
vim.api.nvim_set_hl(0, "TelescopeSelection", {
  bg = "#473f77",
  fg = "#e5deff",
})
vim.api.nvim_set_hl(0, "TelescopeMatching", { fg = C.focus })

---------------------------------------------------------------------
-- Lazy & Mason
---------------------------------------------------------------------
set_hl({ "LazyNormal", "MasonNormal" }, { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "LazyBorder", { bg = C.bg, fg = "#928f99" })

set_hl({
  "LazyHeader",
  "LazyH1",
  "LazyReasonPlugin",
  "MasonTitle",
  "MasonInstalled",
}, {
  bg = "#473f77",
  fg = "#e5deff",
})

---------------------------------------------------------------------
-- LUALINE (theme = nil, semantic contrast)
---------------------------------------------------------------------

-- MODE
vim.api.nvim_set_hl(0, "lualine_a_normal", {
  bg = C.focus,
  fg = C.focus_fg,
  bold = true,
})

vim.api.nvim_set_hl(0, "lualine_a_insert", {
  bg = "#c9c3dc",
  fg = "#312e41",
  bold = true,
})

-- SECTION B
vim.api.nvim_set_hl(0, "lualine_b_normal", {
  bg = C.surface,
  fg = C.focus,
})

-- SECTION C
vim.api.nvim_set_hl(0, "lualine_c_normal", {
  bg = C.surface,
  fg = C.subtle,
})

-- X / Y
vim.api.nvim_set_hl(0, "lualine_x_normal", { fg = C.subtle })
vim.api.nvim_set_hl(0, "lualine_y_normal", { fg = C.focus })

-- Z
vim.api.nvim_set_hl(0, "lualine_z_normal", {
  fg = C.focus,
  bold = true,
})

-- INACTIVE
vim.api.nvim_set_hl(0, "lualine_a_inactive", { fg = C.subtle, bg = C.bg })
vim.api.nvim_set_hl(0, "lualine_b_inactive", { fg = C.subtle, bg = C.bg })
vim.api.nvim_set_hl(0, "lualine_c_inactive", { fg = C.subtle, bg = C.bg })

---------------------------------------------------------------------
-- Messages
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "MsgArea", {
  bg = C.surface2,
  fg = C.focus,
})

