-- Auto-generated by Matugen (Material 3 Expressive)

require('base16-colorscheme').setup({
  base00 = '{{colors.background.default.hex}}',
  base01 = '{{colors.surface_container_lowest.default.hex}}',
  base02 = '{{colors.primary.default.hex}}',
  base03 = '{{colors.outline.default.hex}}',
  base04 = '{{colors.on_surface_variant.default.hex}}',
  base05 = '{{colors.on_surface.default.hex}}',
  base06 = '{{colors.inverse_surface.default.hex}}',
  base07 = '{{colors.surface_bright.default.hex}}',

  base08 = '{{colors.error.default.hex}}',
  base09 = '{{colors.tertiary.default.hex}}',
  base0A = '{{colors.secondary.default.hex}}',
  base0B = '{{colors.primary.default.hex}}',
  base0C = '{{colors.tertiary_container.default.hex}}',
  base0D = '{{colors.primary_container.default.hex}}',
  base0E = '{{colors.secondary_container.default.hex}}',
  base0F = '{{colors.error_container.default.hex}}',
})

-- Helper function
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Material 3 Expressive highlights (FIXED)
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}',
})

-- Comments → tertiary (your request)
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '{{colors.tertiary.default.hex}}',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '{{colors.primary.default.hex}}',
})

-- Keyword with bold style (FIXED syntax)
vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '{{colors.primary.default.hex}}',
  bold = true,  -- ✅ Correct syntax
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '{{colors.surface_container_lowest.default.hex}}',
  fg = '{{colors.primary.default.hex}}',
})


-- Telescope Material 3 Expressive theming
vim.api.nvim_set_hl(0, 'TelescopeNormal', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

vim.api.nvim_set_hl(0, 'TelescopeBorder', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.outline.default.hex}}',  -- Outline for clean borders
})

vim.api.nvim_set_hl(0, 'TelescopePromptBorder', {
  bg = '{{colors.surface_container_low.default.hex}}',
  fg = '{{colors.primary.default.hex}}',   -- Primary accent
})

vim.api.nvim_set_hl(0, 'TelescopePromptNormal', {
  bg = '{{colors.surface_container_low.default.hex}}',
  fg = '{{colors.on_surface_variant.default.hex}}',
})

vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', {
  bg = '{{colors.surface_container_low.default.hex}}',
  fg = '{{colors.primary.default.hex}}',    -- Vibrant prompt cursor
})

vim.api.nvim_set_hl(0, 'TelescopeSelection', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}',  -- Matches Visual
})

vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', {
  bg = '{{colors.primary.default.hex}}',
  fg = '{{colors.primary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', {
  bg = '{{colors.surface_bright.default.hex}}',
  fg = '{{colors.primary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}',
})

vim.api.nvim_set_hl(0, 'TelescopeMatching', {
  fg = '{{colors.primary.default.hex}}',  -- Highlight matches
})

-- Lazy.nvim Material 3 Expressive UI
vim.api.nvim_set_hl(0, 'LazyNormal', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

vim.api.nvim_set_hl(0, 'LazyBorder', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.outline.default.hex}}',  -- Clean outline borders
})

vim.api.nvim_set_hl(0, 'LazyHeader', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}',
})

vim.api.nvim_set_hl(0, 'LazyReasonPlugin', { fg = '{{colors.primary.default.hex}}' })
vim.api.nvim_set_hl(0, 'LazyReasonSource', { fg = '{{colors.secondary.default.hex}}' })
vim.api.nvim_set_hl(0, 'LazyCommit', { fg = '{{colors.tertiary.default.hex}}' })

vim.api.nvim_set_hl(0, 'LazyH1', {
  fg = '{{colors.primary.default.hex}}',
  bold = true,
})

-- Mason.nvim Material 3 Expressive UI  
vim.api.nvim_set_hl(0, 'MasonHeader', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}',
})

vim.api.nvim_set_hl(0, 'MasonHeaderSecondary', {
  bg = '{{colors.surface_bright.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

vim.api.nvim_set_hl(0, 'MasonNormal', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

vim.api.nvim_set_hl(0, 'MasonBorder', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.outline.default.hex}}',
})

vim.api.nvim_set_hl(0, 'MasonTitle', {
  fg = '{{colors.primary.default.hex}}',
  bold = true,
})

vim.api.nvim_set_hl(0, 'MasonInstalled', { fg = '{{colors.primary.default.hex}}' })
vim.api.nvim_set_hl(0, 'MasonUninstalled', { fg = '{{colors.on_surface_variant.default.hex}}' })
vim.api.nvim_set_hl(0, 'MasonCommit', { fg = '{{colors.tertiary.default.hex}}' })

-- Lazy.nvim window highlights (must have ui.border = "rounded")
vim.api.nvim_set_hl(0, 'LazyWin', { bg = '{{colors.background.default.hex}}' })
vim.api.nvim_set_hl(0, 'LazyFloat', { bg = '{{colors.background.default.hex}}' })

-- Mason.nvim window highlights  
vim.api.nvim_set_hl(0, 'MasonNormalFloat', { bg = '{{colors.background.default.hex}}' })
vim.api.nvim_set_hl(0, 'MasonBorder', { fg = '{{colors.outline.default.hex}}' })

-- GLOBAL FLOAT BORDERS (affects Lazy/Mason/Telescope)
vim.api.nvim_set_hl(0, 'FloatBorder', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.outline.default.hex}}',  -- Material 3 outline
})

-- Lazy.nvim specific floats
vim.api.nvim_set_hl(0, 'LazyFloatNormal', {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

-- Mason.nvim specific floats  
vim.api.nvim_set_hl(0, 'MasonFloat', {
  bg = '{{colors.background.default.hex}}',
})

-- Fallback for all plugin floats
vim.api.nvim_set_hl(0, 'NormalFloat', {
  bg = '{{colors.background.default.hex}}',
})

