-- Auto-generated by Matugen (Material 3 Expressive)
-- Neovim Base16 + UI semantic overrides

require("base16-colorscheme").setup({
  -- Base palette
  base00 = "{{colors.background.default.hex}}",
  base01 = "{{colors.surface_container_lowest.default.hex}}",
  base02 = "{{colors.surface_container_low.default.hex}}",
  base03 = "{{colors.outline.default.hex}}",
  base04 = "{{colors.on_surface_variant.default.hex}}",
  base05 = "{{colors.on_surface.default.hex}}",
  base06 = "{{colors.inverse_surface.default.hex}}",
  base07 = "{{colors.surface_bright.default.hex}}",

  -- Syntax
  base08 = "{{colors.error.default.hex}}",
  base09 = "{{colors.tertiary.default.hex}}",
  base0A = "{{colors.secondary.default.hex}}",
  base0B = "{{colors.primary.default.hex}}",
  base0C = "{{colors.tertiary_container.default.hex}}",
  base0D = "{{colors.primary_container.default.hex}}",
  base0E = "{{colors.secondary_container.default.hex}}",
  base0F = "{{colors.error_container.default.hex}}",
})

---------------------------------------------------------------------
-- Helpers
---------------------------------------------------------------------
local function set_hl(groups, opts)
  for _, g in ipairs(groups) do
    vim.api.nvim_set_hl(0, g, opts)
  end
end

---------------------------------------------------------------------
-- Semantic UI tokens (THIS is what was missing)
---------------------------------------------------------------------
local C = {
  bg        = "{{colors.background.default.hex}}",
  surface   = "{{colors.surface_container_low.default.hex}}",
  surface2  = "{{colors.surface_container_lowest.default.hex}}",
  focus     = "{{colors.primary.default.hex}}",
  focus_fg  = "{{colors.on_primary.default.hex}}",
  subtle    = "{{colors.on_surface_variant.default.hex}}",
  text      = "{{colors.on_surface.default.hex}}",
}

---------------------------------------------------------------------
-- Core editor
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "Normal", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "Visual", {
  bg = "{{colors.primary_container.default.hex}}",
  fg = "{{colors.on_primary_container.default.hex}}",
})

vim.api.nvim_set_hl(0, "LineNr", { fg = C.subtle })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = C.focus, bold = true })

---------------------------------------------------------------------
-- Treesitter (modern capture groups)
---------------------------------------------------------------------
set_hl({ "@comment", "Comment" }, { fg = "{{colors.tertiary.default.hex}}", italic = true })
set_hl({ "@function", "Function" }, { fg = "{{colors.primary.default.hex}}" })
set_hl({ "@method" }, { fg = "{{colors.tertiary_container.default.hex}}" })
vim.api.nvim_set_hl(0, "Keyword", { fg = C.focus, bold = true })

---------------------------------------------------------------------
-- Floats
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "NormalFloat", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = C.bg, fg = "{{colors.outline.default.hex}}" })

---------------------------------------------------------------------
-- Telescope
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = C.surface, fg = C.subtle })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = C.surface, fg = C.focus })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { bg = C.surface, fg = C.focus })
vim.api.nvim_set_hl(0, "TelescopeSelection", {
  bg = "{{colors.primary_container.default.hex}}",
  fg = "{{colors.on_primary_container.default.hex}}",
})
vim.api.nvim_set_hl(0, "TelescopeMatching", { fg = C.focus })

---------------------------------------------------------------------
-- Lazy & Mason
---------------------------------------------------------------------
set_hl({ "LazyNormal", "MasonNormal" }, { bg = C.bg, fg = C.text })
vim.api.nvim_set_hl(0, "LazyBorder", { bg = C.bg, fg = "{{colors.outline.default.hex}}" })

set_hl({
  "LazyHeader",
  "LazyH1",
  "LazyReasonPlugin",
  "MasonTitle",
  "MasonInstalled",
}, {
  bg = "{{colors.primary_container.default.hex}}",
  fg = "{{colors.on_primary_container.default.hex}}",
})

---------------------------------------------------------------------
-- LUALINE (theme = nil, semantic contrast)
---------------------------------------------------------------------

-- MODE
vim.api.nvim_set_hl(0, "lualine_a_normal", {
  bg = C.focus,
  fg = C.focus_fg,
  bold = true,
})

vim.api.nvim_set_hl(0, "lualine_a_insert", {
  bg = "{{colors.secondary.default.hex}}",
  fg = "{{colors.on_secondary.default.hex}}",
  bold = true,
})

-- SECTION B
vim.api.nvim_set_hl(0, "lualine_b_normal", {
  bg = C.surface,
  fg = C.focus,
})

-- SECTION C
vim.api.nvim_set_hl(0, "lualine_c_normal", {
  bg = C.surface,
  fg = C.subtle,
})

-- X / Y
vim.api.nvim_set_hl(0, "lualine_x_normal", { fg = C.subtle })
vim.api.nvim_set_hl(0, "lualine_y_normal", { fg = C.focus })

-- Z
vim.api.nvim_set_hl(0, "lualine_z_normal", {
  fg = C.focus,
  bold = true,
})

-- INACTIVE
vim.api.nvim_set_hl(0, "lualine_a_inactive", { fg = C.subtle, bg = C.bg })
vim.api.nvim_set_hl(0, "lualine_b_inactive", { fg = C.subtle, bg = C.bg })
vim.api.nvim_set_hl(0, "lualine_c_inactive", { fg = C.subtle, bg = C.bg })

---------------------------------------------------------------------
-- Messages
---------------------------------------------------------------------
vim.api.nvim_set_hl(0, "MsgArea", {
  bg = C.surface2,
  fg = C.focus,
})
